### ISSUE TITLE
nc2nc: Python 3 clean up needed

### ISSUE THREAD

**Issue by ccarouge** [coecms/nccompress#3]
I have this:
```
nc2nc -d 5 -b 1000 /g/data/w97/dc8106/AMZ_def_EXPs/original/uaoye/work/uaoye.monthly_TS.1978_2011.nc tmp.ncTraceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/bin/nc2nc", line 10, in <module>
    sys.exit(main_argv())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/nccompress/nc2nc.py", line 381, in main_argv
    main_parse_args(sys.argv[1:])
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/nccompress/nc2nc.py", line 375, in main_parse_args
    return main(parse_args(arglist))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/nccompress/nc2nc.py", line 367, in main
    verbose=verbose, vars=args.vars, classic=args.classic, buffersize=args.buffersize, ignoreformat=args.ignoreformat)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/nccompress/nc2nc.py", line 297, in nc2nc
    for index in np.ndindex(*bufferSteps):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/numpy/lib/index_tricks.py", line 638, in __init__
    strides=_nx.zeros_like(shape))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/numpy/lib/stride_tricks.py", line 103, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
Looking into it, the problem is with buffersteps which is calculated:
https://github.com/aidanheerdegen/nccompress/blob/5e4f287cf0ce7eecf3dbdf4ba35c93ae5b5751de/nc2nc#L289-L290

Should there be some integer rounding there or are `dimlim` and `bufferChunk` supposed to divide each other correctly?
It works with a buffer size of 2000.

**Comment by aidanheerdegen** [comment]
I'd guess it is a python3 integer divide issue. Needs a `//`.

**Comment by ccarouge** [comment]
`itertools.izip` also needs to be changed. Working on it. We're stopping support for Python 2 with this update.
