### ISSUE TITLE
Handling of netCDF4 format

### ISSUE THREAD

**Issue by ccarouge** [coecms/nccompress#8]
Could nc2nc call nccopy instead of skipping netCDF4 format files?

**Comment by aidanheerdegen** [comment]
It should definitely tell the user rather than swallow the exception from `nc2nc`

If nc2nc is used directly:
```
$ nc2nc -d 5 -b 1000 ocean_snap_uncomp.nc tmp.nc_compress/ocean_snap_uncomp.nc
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.04/bin/nc2nc", line 10, in <module>
    sys.exit(main_argv())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.04/lib/python3.6/site-packages/nccompress/nc2nc.py", line 381, in main_argv
    main_parse_args(sys.argv[1:])
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.04/lib/python3.6/site-packages/nccompress/nc2nc.py", line 375, in main_parse_args
    return main(parse_args(arglist))
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.04/lib/python3.6/site-packages/nccompress/nc2nc.py", line 367, in main
    verbose=verbose, vars=args.vars, classic=args.classic, buffersize=args.buffersize, ignoreformat=args.ignoreformat)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.04/lib/python3.6/site-packages/nccompress/nc2nc.py", line 193, in nc2nc
    raise FormatError('nc2nc is not tested to work with netCDF4 files, only netCDF4 Classic, and netCDF3. See --ignoreformat option to ignore warning')
nccompress.nc2nc.FormatError: nc2nc is not tested to work with netCDF4 files, only netCDF4 Classic, and netCDF3. See --ignoreformat option to ignore warning
```
but `nccompress` doesn't tell the user this.
